
name: Create/Delete/Reset Branch for Pull Request Workflow
run-name: Create/Delete/Reset Branch for Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      - labeled

jobs:
  neon_branch_management:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
    steps: 
      - id: step1
        run: |
          echo "output1=1" >> $GITHUB_OUTPUT
  db_usage_example:
    needs: neon_branch_management
    runs-on: ubuntu-latest
    steps: 
      - name: Connect to DB
        run: |
          echo '${{ toJSON(needs) }}'
          
      
