
name: Create/Delete/Reset Branch for Pull Request Workflow
run-name: Create/Delete/Reset Branch for Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      - labeled

jobs:
  neon_branch_management:
    uses: neondatabase/reusable-workflows/.github/workflows/neon-preview-branches-for-pull-requests.yml@bug/14341/neon_branch_naming
    with:
      project_id: "summer-resonance-39584310"
      api_url: "https://console-stage.neon.build/api/v2"
    secrets:
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  db_usage_example:
    needs:
      - neon_branch_management
    runs-on: ubuntu-latest
    if: jobs.neon_branch_management.outputs.database_url != ""
    steps: 
      - name: Connect to DB
        run: |
          apt-get install --yes --no-install-recommends postgresql-client
          psql -c 'SHOW DATABASES' "${{ jobs.neon_branch_management.outputs.database_url }}"
      
