
name: Create/Delete/Reset Branch for Pull Request Workflow
run-name: Create/Delete/Reset Branch for Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      - labeled
  workflow_dispatch:    

jobs:
  neon_branch_management:
    uses: neondatabase/reusable-workflows/.github/workflows/neon-preview-branches-for-pull-requests.yml@feat/14361/job_outputs
    with:
      project_id: "summer-resonance-39584310"
      api_url: "https://console-stage.neon.build/api/v2"
    secrets:
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}  
  db_usage_example:
    needs: neon_branch_management
    runs-on: ubuntu-latest
    steps: 
      - name: Connect to DB
        run: |
          db_url=$(gpg --decrypt --quiet --batch --passphrase "passcode" --output - <(echo '${{ needs.neon_branch_management.outputs.db_url }}' | base64 --decode))
          echo $db_url
          
      
